version: "3"

services:
  admin-app:
    build:
      context: .
      dockerfile: apps/admin-app/Dockerfile
    ports:
      - "3000:3000"

  user-app:
    build:
      context: .
      dockerfile: apps/user-app/Dockerfile
    ports:
      - "3001:3001"

  express-app:
    build:
      context: .
      dockerfile: apps/express-app/Dockerfile
    ports:
      - "5000:5000"
