name: Build on PR or Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check for Prisma Changes
        id: prisma_changes
        run: |
          if git diff --quiet HEAD^ HEAD ./prisma; then
            echo "::set-output name=prisma_changed::false"
          else
            echo "::set-output name=prisma_changed::true"
          fi

      - name: Run Migrations
        if: steps.prisma_changes.outputs.prisma_changed == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run prisma:migrate

      - name: Generate Prisma client
        if: steps.prisma_changes.outputs.prisma_changed == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run prisma:generate

      - name: Run Build
        run: pnpm run build
