name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Prisma CLI
        run: pnpm install -g prisma

      - name: Generate Prisma Client
        run: prisma generate

      - name: Generate prisma client
        run: pnpm run prisma:generate

      - name: Run Build
        run: pnpm run build
