name: Build and Deploy to EC2 via DockerHub and Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out Repo
      - name: Check Out Repo
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/express-app/Dockerfile
          push: true
          tags: rahuldev7583/course-backend:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      # Step 4: Verify Pushed Image
      - name: Verify Pushed Image
        run: docker pull rahuldev7583/course-backend:latest

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull rahuldev7583/course-backend:latest
            sudo docker stop course-backend || true
            sudo docker rm course-backend || true
            sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true
            sudo docker run -d --name course-backend -p 5000:5000 \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e SECRET=${{ secrets.SECRET }} \
            -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e ADMIN_APP=${{secrets.ADMIN_APP}} \
            -e VERCEL_ADMIN_APP=${{secrets.VERCEL_ADMIN_APP}} \
            -e USER_APP=${{secrets.USER_APP}} \
            -e VERCEL_USER_APP=${{secrets.VERCEL_USER_APP}} \
            rahuldev7583/course-backend:latest
